apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend   # Use the label that matches your backend deployment
  ports:
    - protocol: TCP
      port: 3000    # The port your backend service is listening on
      targetPort: 3000
  type: ClusterIP   # Use "ClusterIP" for internal service communication
